# dependencies
# gems: jekyll-paginate
# Site settings
title: Riccardo Casatta
email: riccardo.casatta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Creative Engineer
baseurl: / # the subpath of your site, e.g. /blog
url: http://rcasatta.github.io # the base hostname & protocol for your site
twitter_username: RCasatta
github_username:  RCasatta

# Build settings
#markdown: kramdown
#paginate: 5


github:
  repo:           https://github.com/RCasatta/rcasatta.github.io
